name: Build
on:
  push:
    branches:
    - master
    - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - id: Build
      run: |
        pnpm install
        pnpm build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: waka.pivotstudio.cn
